name: Promote edge -> stable

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Promote snap to stable
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
        run: |
          sudo snap install --classic charmcraft
          charmcraft promote --from-channel latest/edge --to-channel latest/stable --yes
