name: Pull Request
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: ./.github/workflows/build-and-test.yaml
    secrets:
      CHARMHUB_TOKEN: "${{ secrets.CHARMHUB_TOKEN }}"
